version: '3.8'

volumes:
  rustdesk-data:

services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r rustdesk.trilinksoftware.com.br:21117 -k _
    volumes:
      - rustdesk-data:/root
    network_mode: "host"
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr -k _
    volumes:
      - rustdesk-data:/root
    network_mode: "host"
    restart: unless-stopped
